on:
  push:
    tags:
      - 'v*.*.*-rc*'
name: Create Pre-Release

jobs:
  build:
    name: Pre-Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Remove unwanted files
        run: |
          Remove-Item -Recurse -Force .github
          Remove-Item -Recurse -Force images
          Remove-Item -Force .gitignore

      - name: Compress files
        run: |
          Get-Location | Compress-Archive -DestinationPath BetterFireGrenade.zip -Force
  
      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name:  ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Deploy Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: BetterFireGrenade.zip
          tags: true
          prerelease: true
          branches: dev